Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,41 @@ name: Node.js CI
 on:
   push:
     branches:
+      - main  # O workflow será acionado em push na branch 'main'name: Node.js CI
+
+on:
+  push:
+    branches:
       - main  # O workflow será acionado em push na branch 'main'
+  pull_request:
+    branches:
+      - main  # Também será acionado para pull requests para a branch 'main'
+
+jobs:
+  build:
+    runs-on: ubuntu-latest  # O job será executado em uma máquina Ubuntu
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3  # Faz o checkout do código do repositório
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '17'  # Versão do Node.js que você está utilizando
+
+      - name: Install dependencies
+        run: |
+          npm install  # Instala as dependências do projeto
+
+      - name: Run Prettier
+        run: |
+          npm run prettier:format || echo "Prettier failed"  # Formata o código com o Prettier
+          
+      - name: Run Lint
+        run: |
+          npm run lint:fix || echo "Linting failed"  # Corrige problemas de lint com o ESLint
+
   pull_request:
     branches:
       - main  # Também será acionado para pull requests para a branch 'main'
